url: https://actif-cea.github.io/
# url: 127.0.0.1:4000/
baseurl: /
# baseurl: #

# Site settings
title: ACTIF CEA
email: actif.cea@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Lang Translation
translate_langs:
  - lang: en
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English
  - lang: fr
    img: https://cdn.countryflags.com/thumbs/france/flag-400.png
    text: French

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1s
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/actifcea/
  - title: linkedin
    url: https://www.linkedin.com/groups/4756440/
  - title: github
    url: https://github.com/Actif-CEA/Actif-CEA.github.io

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty