url: https://actif-cea.github.io/
url: 127.0.0.1:4000/
# baseurl: /
# baseurl: #

# Site settings
title: ACTIF CEA
email: actif.cea@gmail.com
description: "L'Association CEA des Thésards d'Île-de-France (ACTIF) a pour objectifs d'accompagner les étudiants et jeunes chercheurs au CEA."

# Lang Translation
translate_langs:
  - lang: en
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English
  - lang: fr
    img: https://cdn.countryflags.com/thumbs/france/flag-400.png
    text: French

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/actifcea/
  - title: linkedin
    url: https://www.linkedin.com/company/actif-cea/
  - title: github
    url: https://github.com/Actif-CEA/Actif-CEA.github.io

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty